export const CollabraChainFactoryABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_reputationContract",
        type: "address",
        internalType: "address",
      },
      { name: "_usdcToken", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allProjects",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createProject",
    inputs: [
      { name: "_title", type: "string", internalType: "string" },
      { name: "_description", type: "string", internalType: "string" },
      { name: "_category", type: "string", internalType: "string" },
      {
        name: "_skillsRequired",
        type: "string[]",
        internalType: "string[]",
      },
      { name: "_totalBudget", type: "uint256", internalType: "uint256" },
      { name: "_deadline", type: "uint256", internalType: "uint256" },
      {
        name: "_projectScopeCID",
        type: "string",
        internalType: "string",
      },
      { name: "_xmtpRoomId", type: "string", internalType: "string" },
    ],
    outputs: [
      { name: "projectAddress", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getProjectCountByXmtpRoom",
    inputs: [{ name: "_xmtpRoomId", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProjectsByXmtpRoom",
    inputs: [{ name: "_xmtpRoomId", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProjectsCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getXmtpRoomForProject",
    inputs: [
      {
        name: "_projectAddress",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isProject",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mintReputationForProject",
    inputs: [
      { name: "recipient", type: "address", internalType: "address" },
      { name: "projectId", type: "uint256", internalType: "uint256" },
      { name: "role", type: "string", internalType: "string" },
      { name: "metadataCID", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "projectToXmtpRoom",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "projectsByXmtpRoom",
    inputs: [
      { name: "", type: "string", internalType: "string" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reputationContract",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IReputation" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdcToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "ProjectCreated",
    inputs: [
      {
        name: "projectAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "title",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "category",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "totalBudget",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "projectScopeCID",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "xmtpRoomId",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "UnauthorizedProject", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
