export const CollabraChainProjectABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_creator",
        type: "address",
        internalType: "address payable",
      },
      {
        name: "_reputationContract",
        type: "address",
        internalType: "address",
      },
      { name: "_factory", type: "address", internalType: "address" },
      { name: "_usdcToken", type: "address", internalType: "address" },
      { name: "_title", type: "string", internalType: "string" },
      { name: "_description", type: "string", internalType: "string" },
      { name: "_category", type: "string", internalType: "string" },
      {
        name: "_skillsRequired",
        type: "string[]",
        internalType: "string[]",
      },
      { name: "_totalBudget", type: "uint256", internalType: "uint256" },
      { name: "_deadline", type: "uint256", internalType: "uint256" },
      {
        name: "_projectScopeCID",
        type: "string",
        internalType: "string",
      },
      { name: "_xmtpRoomId", type: "string", internalType: "string" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addMilestone",
    inputs: [
      { name: "_description", type: "string", internalType: "string" },
      { name: "_budget", type: "uint256", internalType: "uint256" },
      { name: "_deadline", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "agentToArbiter",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "agentToCreator",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "agentToFreelancer",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "applicantList",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "applicants",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "applyProject",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approveFreelancer",
    inputs: [
      {
        name: "_approvedFreelancer",
        type: "address",
        internalType: "address payable",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "arbiter",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "arbiterDelegates",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelProject",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "completedAt",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createdAt",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creatorDelegates",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "delegateArbiterToAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "delegateCreatorToAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "delegateFreelancerToAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "freelancer",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address payable" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "freelancerDelegates",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundMilestone",
    inputs: [
      { name: "_milestoneId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAgentInfo",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "delegatingCreator",
        type: "address",
        internalType: "address",
      },
      {
        name: "delegatingFreelancer",
        type: "address",
        internalType: "address",
      },
      {
        name: "delegatingArbiter",
        type: "address",
        internalType: "address",
      },
      { name: "isCreatorAgent", type: "bool", internalType: "bool" },
      { name: "isFreelancerAgent", type: "bool", internalType: "bool" },
      { name: "isArbiterAgent", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllMilestones",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct CollabraChainProject.Milestone[]",
        components: [
          { name: "description", type: "string", internalType: "string" },
          { name: "budget", type: "uint256", internalType: "uint256" },
          {
            name: "state",
            type: "uint8",
            internalType: "enum CollabraChainProject.MilestoneState",
          },
          {
            name: "workSubmissionCID",
            type: "string",
            internalType: "string",
          },
          { name: "deadline", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getApplicants",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMilestone",
    inputs: [
      { name: "_milestoneId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct CollabraChainProject.Milestone",
        components: [
          { name: "description", type: "string", internalType: "string" },
          { name: "budget", type: "uint256", internalType: "uint256" },
          {
            name: "state",
            type: "uint8",
            internalType: "enum CollabraChainProject.MilestoneState",
          },
          {
            name: "workSubmissionCID",
            type: "string",
            internalType: "string",
          },
          { name: "deadline", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProjectMetadata",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct CollabraChainProject.ProjectMetadata",
        components: [
          { name: "title", type: "string", internalType: "string" },
          { name: "description", type: "string", internalType: "string" },
          { name: "category", type: "string", internalType: "string" },
          {
            name: "skillsRequired",
            type: "string[]",
            internalType: "string[]",
          },
          {
            name: "totalBudget",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "deadline", type: "uint256", internalType: "uint256" },
          {
            name: "projectScopeCID",
            type: "string",
            internalType: "string",
          },
          { name: "xmtpRoomId", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProjectStatus",
    inputs: [],
    outputs: [
      {
        name: "state",
        type: "uint8",
        internalType: "enum CollabraChainProject.ProjectState",
      },
      {
        name: "currentFreelancer",
        type: "address",
        internalType: "address",
      },
      {
        name: "milestonesCount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "completedMilestones",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "totalBudget", type: "uint256", internalType: "uint256" },
      { name: "paidAmount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProjectTimeline",
    inputs: [],
    outputs: [
      { name: "created", type: "uint256", internalType: "uint256" },
      { name: "started", type: "uint256", internalType: "uint256" },
      { name: "completed", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getXmtpRoomId",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasApplied",
    inputs: [{ name: "_applicant", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "inviteFreelancer",
    inputs: [{ name: "_freelancer", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isAuthorizedArbiterAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAuthorizedCreatorAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAuthorizedFreelancerAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "milestones",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "description", type: "string", internalType: "string" },
      { name: "budget", type: "uint256", internalType: "uint256" },
      {
        name: "state",
        type: "uint8",
        internalType: "enum CollabraChainProject.MilestoneState",
      },
      {
        name: "workSubmissionCID",
        type: "string",
        internalType: "string",
      },
      { name: "deadline", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "projectMetadata",
    inputs: [],
    outputs: [
      { name: "title", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "category", type: "string", internalType: "string" },
      { name: "totalBudget", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "projectScopeCID", type: "string", internalType: "string" },
      { name: "xmtpRoomId", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "projectState",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum CollabraChainProject.ProjectState",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "raiseDispute",
    inputs: [
      { name: "_milestoneId", type: "uint256", internalType: "uint256" },
      { name: "_reason", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releasePayment",
    inputs: [
      { name: "_milestoneId", type: "uint256", internalType: "uint256" },
      { name: "_creatorSbtCID", type: "string", internalType: "string" },
      {
        name: "_freelancerSbtCID",
        type: "string",
        internalType: "string",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reputationContract",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolveDispute",
    inputs: [
      { name: "_milestoneId", type: "uint256", internalType: "uint256" },
      { name: "_payFreelancer", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeArbiterAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeCreatorAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeFreelancerAgent",
    inputs: [{ name: "_agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "startedAt",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "submitWork",
    inputs: [
      { name: "_milestoneId", type: "uint256", internalType: "uint256" },
      { name: "_workCID", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usdcToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AgentDelegated",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "agent",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "role",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentRevoked",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "agent",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "role",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Applied",
    inputs: [
      {
        name: "applicant",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      {
        name: "milestoneId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      {
        name: "milestoneId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "payFreelancer",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "arbiter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FreelancerApproved",
    inputs: [
      {
        name: "freelancer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MilestoneAdded",
    inputs: [
      {
        name: "milestoneId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "description",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "budget",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MilestoneFunded",
    inputs: [
      {
        name: "milestoneId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentReleased",
    inputs: [
      {
        name: "milestoneId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProjectCanceled",
    inputs: [
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProjectCompleted",
    inputs: [
      {
        name: "completedAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProjectCreated",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "title",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "category",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "totalBudget",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "xmtpRoomId",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProjectInvitation",
    inputs: [
      {
        name: "invitee",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProjectStarted",
    inputs: [
      {
        name: "freelancer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReputationTokenMinted",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "role",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "sbtCID",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WorkApproved",
    inputs: [
      {
        name: "milestoneId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WorkSubmitted",
    inputs: [
      {
        name: "milestoneId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "workCID",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "freelancer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyApplied", inputs: [] },
  { type: "error", name: "CannotDelegateSelf", inputs: [] },
  {
    type: "error",
    name: "InvalidAmount",
    inputs: [
      { name: "sent", type: "uint256", internalType: "uint256" },
      { name: "expected", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "InvalidDeadline", inputs: [] },
  { type: "error", name: "InvalidState", inputs: [] },
  { type: "error", name: "MilestoneNotFound", inputs: [] },
  { type: "error", name: "NotAuthorizedAgent", inputs: [] },
  { type: "error", name: "ProjectNotFound", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
